/* global variables */
var turn = "W";

/* initial game board setup */
var table = document.createElement('table');
for(var y = 0; y < 3; y++) {
  var row = document.createElement('tr');
  for(var x = 0; x < 3; x++) {
    var data = document.createElement('td');
    data.id = 'square-' + x + '-' + y;
    data.dataset.x = x;
    data.dataset.y = y;
    data.addEventListener('click', placeMark);
    row.appendChild(data);
  }
  table.appendChild(row);
}
document.body.appendChild(table);

/** @function placeMark
  * Places the current player's mark on the tic-tac-toe board.
  * @param {MouseEvent} event - the event generated by clicking
  * on the listening element
  */
function placeMark(event) {
  event.target.innerHTML = turn;
  checkForWin();
  turn = (turn === "W") ?  "3" : "W";
  event.target.removeEventListener('click', placeMark);
}

/** @function checkForWin
  * Checks for a winner after a player takes their
  * turn.
  */
function checkForWin() {
  // check for diagonal down
  if(document.getElementById('square-0-0').innerHTML === turn &&
     document.getElementById('square-1-1').innerHTML === turn &&
     document.getElementById('square-2-2').innerHTML === turn)
  {
    alert(turn + " wins!");
    return;  // Exits the function early
  }

  //check for diagonal up
  if(document.getElementById('square-2-0').innerHTML === turn &&
     document.getElementById('square-1-1').innerHTML === turn &&
     document.getElementById('square-0-2').innerHTML === turn)
  {
    alert(turn + " wins!");
    return;  // Exits the function early
  }
  
  //check for horizontal row
  for(i = 0; i < 3; i++){
		if(document.getElementById('square-'+i+'-0').innerHTML === turn &&
			document.getElementById('square-'+i+'-1').innerHTML === turn &&
			document.getElementById('square-'+i+'-2').innerHTML === turn)
		{
			alert(turn + " wins!");
			return;  // Exits the function early
		}
  }
  // HINT: you can place this check inside a for loop

  //check for vertical row
  for(i = 0; i < 3; i++){
		if(document.getElementById('square-0-'+i).innerHTML === turn &&
			document.getElementById('square-1-'+i).innerHTML === turn &&
			document.getElementById('square-2-'+i).innerHTML === turn)
		{
			alert(turn + " wins!");
			return;  // Exits the function early
		}
  }

}
